defaults:
  - scope:
      path: "/index.json"
    values:
      permalink: "http://redirect.nekosunevr.co.uk:7300/index.json"
  - scope:
      path: "/source.json"
    values:
      permalink: "http://redirect.nekosunevr.co.uk:7300/source.json"
